## Ana Riaz i202483

# Task 1

In [245]:
import numpy as np
import pandas as pd
import random

In [246]:
df= pd.read_csv("Advertising.csv")
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [247]:
# putting the "sales" coulmn in Y
Y = df.iloc[:,-1:]
Y = np.array(Y)
print(Y)

[[22.1]
 [10.4]
 [ 9.3]
 [18.5]
 [12.9]
 [ 7.2]
 [11.8]
 [13.2]
 [ 4.8]
 [10.6]
 [ 8.6]
 [17.4]
 [ 9.2]
 [ 9.7]
 [19. ]
 [22.4]
 [12.5]
 [24.4]
 [11.3]
 [14.6]
 [18. ]
 [12.5]
 [ 5.6]
 [15.5]
 [ 9.7]
 [12. ]
 [15. ]
 [15.9]
 [18.9]
 [10.5]
 [21.4]
 [11.9]
 [ 9.6]
 [17.4]
 [ 9.5]
 [12.8]
 [25.4]
 [14.7]
 [10.1]
 [21.5]
 [16.6]
 [17.1]
 [20.7]
 [12.9]
 [ 8.5]
 [14.9]
 [10.6]
 [23.2]
 [14.8]
 [ 9.7]
 [11.4]
 [10.7]
 [22.6]
 [21.2]
 [20.2]
 [23.7]
 [ 5.5]
 [13.2]
 [23.8]
 [18.4]
 [ 8.1]
 [24.2]
 [15.7]
 [14. ]
 [18. ]
 [ 9.3]
 [ 9.5]
 [13.4]
 [18.9]
 [22.3]
 [18.3]
 [12.4]
 [ 8.8]
 [11. ]
 [17. ]
 [ 8.7]
 [ 6.9]
 [14.2]
 [ 5.3]
 [11. ]
 [11.8]
 [12.3]
 [11.3]
 [13.6]
 [21.7]
 [15.2]
 [12. ]
 [16. ]
 [12.9]
 [16.7]
 [11.2]
 [ 7.3]
 [19.4]
 [22.2]
 [11.5]
 [16.9]
 [11.7]
 [15.5]
 [25.4]
 [17.2]
 [11.7]
 [23.8]
 [14.8]
 [14.7]
 [20.7]
 [19.2]
 [ 7.2]
 [ 8.7]
 [ 5.3]
 [19.8]
 [13.4]
 [21.8]
 [14.1]
 [15.9]
 [14.6]
 [12.6]
 [12.2]
 [ 9.4]
 [15.9]
 [ 6.6]
 [15.5]
 [ 7. ]
 [11.6]
 [15.2]
 [19.7]


In [248]:
# selecting all the columns except first two in X
X = df.iloc[: , 1:-1]
# adding a column of ones in the training dataset with dim= dx1

X['X_not'] = np.ones (200)
X = np.array(X)
print(X)

[[230.1  37.8  69.2   1. ]
 [ 44.5  39.3  45.1   1. ]
 [ 17.2  45.9  69.3   1. ]
 [151.5  41.3  58.5   1. ]
 [180.8  10.8  58.4   1. ]
 [  8.7  48.9  75.    1. ]
 [ 57.5  32.8  23.5   1. ]
 [120.2  19.6  11.6   1. ]
 [  8.6   2.1   1.    1. ]
 [199.8   2.6  21.2   1. ]
 [ 66.1   5.8  24.2   1. ]
 [214.7  24.    4.    1. ]
 [ 23.8  35.1  65.9   1. ]
 [ 97.5   7.6   7.2   1. ]
 [204.1  32.9  46.    1. ]
 [195.4  47.7  52.9   1. ]
 [ 67.8  36.6 114.    1. ]
 [281.4  39.6  55.8   1. ]
 [ 69.2  20.5  18.3   1. ]
 [147.3  23.9  19.1   1. ]
 [218.4  27.7  53.4   1. ]
 [237.4   5.1  23.5   1. ]
 [ 13.2  15.9  49.6   1. ]
 [228.3  16.9  26.2   1. ]
 [ 62.3  12.6  18.3   1. ]
 [262.9   3.5  19.5   1. ]
 [142.9  29.3  12.6   1. ]
 [240.1  16.7  22.9   1. ]
 [248.8  27.1  22.9   1. ]
 [ 70.6  16.   40.8   1. ]
 [292.9  28.3  43.2   1. ]
 [112.9  17.4  38.6   1. ]
 [ 97.2   1.5  30.    1. ]
 [265.6  20.    0.3   1. ]
 [ 95.7   1.4   7.4   1. ]
 [290.7   4.1   8.5   1. ]
 [266.9  43.8   5.    1. ]
 

### Initializing Alpha and Thetas

In [249]:
# Since number of thetas = number of features + 1 
# but the addition of a "ones" column in the datset makes it -> number of thetas = number of features
alpha = 0.0001
thetas = np.array([[80] , [50] , [65] , [1]])


### Defining  Functions 

In [250]:
def hypothesis(X1,thetas1):
    return np.dot(X1,thetas1)

In [251]:
def loss_fun(y_act,y_pred):
    return np.mean((y_act-y_pred)**2)

In [252]:
def gradient_descent(alpha,thetas2,g_thetas):
    return (thetas2-alpha*g_thetas)

In [253]:
def der_loss_fun(x,y,thetas3):
    hp=hypothesis(x,thetas3)
    diff = (y-hp).T
    f1=np.dot(diff,X)
    f1=-2*f1/float(x.shape[0])
    return f1

In [254]:
### checking if all our made arrays have consistent shapes
print(X.shape)
print(Y.shape)
print(thetas.shape)

(200, 4)
(200, 1)
(4, 1)


### caluculating predicted Y

In [255]:
y_pred = hypothesis(X,thetas)
y_pred.shape

(200, 1)

In [256]:
Y.shape

(200, 1)

### Finding Mean Squared Error

In [257]:
mse = loss_fun(Y,y_pred)
mse

273807280.85225

### derivative of loss function

In [258]:
gradient_thetas = der_loss_fun(X,Y,thetas)
gradient_thetas = gradient_thetas.T
gradient_thetas.shape


(4, 1)

### updating thetas

In [259]:
new_thetas =gradient_descent(0.001,thetas,gradient_thetas)

In [260]:
new_thetas

array([[-5495.1551356],
       [ -691.0240356],
       [ -935.0389777],
       [  -28.799175 ]])

In [261]:
h1 = hypothesis(X,new_thetas)

In [262]:
loss_fun(Y,h1)

950858354641.2578

In [263]:
# gradient descent for 100 iterrations
for i in range(100):
    y_pred = hypothesis(X , new_thetas)
    gradient_thetas = der_loss_fun(X , Y , new_thetas)
    gradient_thetas = gradient_thetas.T
    new_thetas = gradient_descent (alpha , new_thetas , gradient_thetas)
    print(loss_fun(Y , y_pred))

950858354641.2578
24036853336430.324
607630940665839.2
1.5360387082404398e+16
3.882973623229461e+17
9.815823050667287e+18
2.4813555669209737e+20
6.272653263723268e+21
1.585672746438412e+23
4.0084441991060776e+24
1.0133001865256718e+26
2.561535640790366e+27
6.475341588100138e+28
1.6369106099824421e+30
4.137969107293452e+31
1.0460429682900416e+33
2.6443065744024763e+34
6.684579382870386e+35
1.6898041232602855e+37
4.27167935547999e+38
1.0798437679763712e+40
2.72975208624099e+41
6.900578281153811e+42
1.7444067853027656e+44
4.4097101846101126e+45
1.114736773331176e+47
2.8179585999860214e+48
7.123556754573876e+49
1.800773823855567e+51
4.552201205670579e+52
1.1507572768100584e+54
2.9090153319271586e+55
7.353740334230411e+56
1.858962251239221e+58
4.699296540899747e+59
1.1879417112741852e+61
3.003014381201074e+62
7.591361838812504e+63
1.9190309220140923e+65
4.8511449695596765e+66
1.2263276868402298e+68
3.100050822945024e+69
7.836661610082509e+70
1.9810405925087024e+72
5.00790007841861e+73
1.265

In [264]:
# final thetas
gradient_thetas

array([[9.06672173e+77],
       [1.11883621e+77],
       [1.48307039e+77],
       [4.66032013e+75]])

In [265]:
thetas

array([[80],
       [50],
       [65],
       [ 1]])

The original thetas and final thetas tell the linear relationship between features and outputs

# Task 2

In [279]:
arr1 = np.array([[1,2,3,4,5] , [1,1,1,1,1]]).T
arr2 = np.array([[3],[5],[7],[9],[11]])
n_thetas = np.array([[10] , [1]])
old_thetas = n_thetas
alpha = 0.06

In [280]:
for i in range(100):
    y_pred = hypothesis(arr1 , n_thetas)
    grad_thetas = der_loss_fun(arr1 , arr2 , n_thetas)
    grad_thetas = grad_thetas.T
    n_thetas = gradient_descent (alpha , n_thetas , grad_thetas)
    print(loss_fun(arr2 , y_pred))

704.0
124.62079999999989
22.53307904
4.526014988288001
1.3315374426619875
0.7473432991227491
0.6238383934344662
0.5823155443783324
0.5560284691710253
0.5331872609382357
0.511684410063526
0.4911192872140294
0.47139312665840566
0.4524614711128782
0.43429051695021714
0.41684938032927843
0.4001086929077052
0.3840403142564499
0.36861724260720313
0.3538135620879926
0.33960439787413393
0.32596587416140055
0.3128750740068681
0.30031000081423687
0.2882495413714894
0.2766734303739361
0.265562216372195
0.2548972290877269
0.2446605480409904
0.2348349724394858
0.22540399227510388
0.21635176058220013
0.20766306680978636
0.1993233112631016
0.191318480571601
0.18363512414216024
0.17626033155791362
0.16918171088475806
0.16238736784906926
0.15586588585164085
0.14960630678426223
0.14359811261670735
0.1378312077231876
0.13229590191857585
0.1269828941758951
0.12188325699771804
0.11698842141520291
0.11229016258957818
0.10778058599186573
0.10345211413762898
0.0992974738544542
0.09530968406076896
0.0914820440

In [281]:
print ("Old Thetas:\n", old_thetas)
print("\nNew Thetas:\n", n_thetas)

Old Thetas:
 [[10]
 [ 1]]

New Thetas:
 [[2.07342398]
 [0.73491614]]


# Task 3

Because classification issues demand discrete data rather than continuous values, linear regression is not appropriate.

# Task 4

MSE is used to check how close estimates or forecasts are to actual values. Lower the MSE, the closer is the prediction to the actual.The MSE is equal to 0 when a model is error-free. Its value increases when model error increases as well. Therefore, it serves as an easy metric for estimation

# Task 5

MSE incorporates two components, one measuring the precision of the estimator and the other measuring its accuracy so, there isn't a better estimator than mse